.alexrc.js, package.json, yarn.lock
config came from the react-native site's config, but I didn't add the exception cases from there, we can do that as exceptions come up if needed.
closes #1
=> added alex with profanity config from react-native

CODE_OF_CONDUCT.md, LICENSE
=> docs: Add license and code of conduct

.github/workflows/main.yml
- Build and lint on pull request to master or push to master
- Closes #19
=> Add initial Github actions workflow

docs/basics/custom-api-routes.md, docs/basics/deploying.md, docs/basics/getting-started.md, docs/basics/pages-and-routing.md, docs/basics/queries-and-mutations.md, docs/basics/webpack-config.md, docs/cli/commands.md, docs/contributing/future-of-blitz.md, package.json, sidebars.js, yarn.lock
This PR adds @flybayer's alpha user docs. This includes CLI & getting started documentation.
Linked Issue: #24
=> Alpha User Documentation

docusaurus.config.js, yarn.lock
#33 - Removed Blog and Vision link, added Manifesto, edited github link to point to blitzJS repository.
#27 - Removed Blog, Stack overflow and Discord link, added Slack link, updated copyrights.
=> #33 Update Nav bar & #27 Update footer

src/pages/index.js, src/pages/styles.module.css
Ok I had anticipated on making some more quick wins 🤣 , but those were all inside theme components. Didn't want to touch on them since they're not stable yet. 
So this has been a nice introduction into Docusaurus and Infima, and as an outcome I think the added vertical space gives some more 'breathing space'  to the features section. 
Let me know what you think @merelinguist
=> Add more vertical space to features section.

src/components/VideoPlayer/video-player.css
As discussed with @robdrosenberg in https://github.com/blitz-js/blitzjs.com/pull/42#issuecomment-620845293 . 
My solution reads a bit hacky 🤓 so if somebody has suggestions to make it cleaner or better readable i'd love to hear!
=> Make sure the video height doesn't exceed the viewports height.

docs/advanced/rpc-specification.md, docs/basics/queries-and-mutations.md, sidebars.js, yarn.lock
Creates some initial documentation for the RPC specification as requested at https://github.com/blitz-js/blitz/issues/85
It's pretty barebones and copied almost verbatim from the slack comments currently, but I expect we'll have more opportunities to polish up the documentation as the design solidifies.
Resolves #21
=> Document the RPC specification (#21)

docs/basics/getting-started.md
Minor change to the getting started documentation.
=> Docs: Changes to installing with Yarn

.github/workflows/main.yml, docusaurus.config.js, package.json, yarn.lock
This is in preparation for creating our own custom theme
=> Remove preset-classic and inline everything into our project

docs/query-usage.mdx
simple typo correction, from way to may
=> Update query-usage.mdx because of a small typo

docs/document-component.mdx
Heya,
I was going through the docs and saw this page wasn't updated yet.
I added some small updates: `NextScript` to `BlitzScript` and `Head` to `DocumentHead`
=> Updated document page

docs/why-blitz.mdx
=> Fix typo in scaffolding section

docs/use-infinite-query.mdx, docs/use-paginated-query.mdx
Update docs according https://github.com/blitz-js/blitz/pull/658
=> Update docs with new Prisma 2 pagination

README.md
Re: https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/
Closes #89
=> Removes references to "master" 

docs/mutation-usage.mdx, docs/use-infinite-query.mdx, docs/use-query.mdx
Add docs for Optimistic Updates, including new refetch option for local mutate() calls.
=> Add Optimistic Updates section and details for refetch option in useQuery mutate()

docs/mutation-usage.mdx
Fixed typo in mutation-usage.mdx
=> Fixed typo in mutation-usage.mdx

docs/error-pages.mdx
For https://github.com/blitz-js/blitz/pull/808
=> Update docs for new error component name

docs/app-component.mdx, docs/error-handling.mdx, sidebars.js
Includes change for https://github.com/blitz-js/blitz/pull/811
=> Add error handling documentation

docs/auth.mdx, sidebars.js, src/css/custom.css, src/pages/index.js
The basics are documented. This PR will remain open until auth is officially released publicly.
Feel free to submit PRs to this one to improve the auth documentation.
=> Add docs for Auth

docs/query-usage.mdx, docs/use-infinite-query.mdx, docs/use-paginated-query.mdx, docs/use-query.mdx
For https://github.com/blitz-js/blitz/pull/874
=> Update docs on `retry` for useQuery

docs/code-splitting.mdx, docs/error-handling.mdx, docs/manifesto.mdx, docs/mutation-definition.mdx, docs/query-definition.mdx
=> Fix capitalization of JavaScript

docs/tutorial.mdx
This note can help zsh users following the tutorial until https://github.com/blitz-js/blitz/issues/724 is fixed 😃
=> Add note for zsh users running generate command with default values

docs/why-blitz.mdx
Auth is now built-in, so there is no need to have “coming soon” any more :)
=> Remove outdated auth caveat

docs/cli-autocomplete.mdx, sidebars.js
Adds documentation for the command created here:
https://github.com/blitz-js/blitz/pull/928
=> Add documentation for the new cli command

docs/environment-variables.mdx, sidebars.js
For https://github.com/blitz-js/blitz/pull/979
=> add docs for environment variables

docs/deploy-vercel.mdx
Prisma works fine in the default "Transaction" mode.
=> Update Vercel deployment: DO transaction mode

docs/database-overview.mdx, docs/tutorial.mdx
Closes https://github.com/blitz-js/blitz/issues/1000
=> Document switching to PostgreSQL

docs/passportjs.mdx
Documentation for the added `authenticateOptions`.
=> Explain authenticateOptions.

docs/tutorial.mdx
=> The code belonging to Issue 160

src/pages/index.js
I replaced it with the Norfolk Developers talk about Blitz
https://www.youtube.com/watch?v=UsJl7Mn5Y0E <- this is the new video
=> Replace deleted video

docs/cli-db.mdx
Docs for https://github.com/blitz-js/blitz/pull/1107
=> Add docs for --force flag of 'blitz db reset' command

docs/contributing.mdx
Add a little guide on troubleshooting about this issue. Closes: https://github.com/blitz-js/blitz/issues/169
=> Add guide on troubleshooting about yarn policies error

docs/cli-db.mdx, docs/database-seeds.mdx, sidebars.js
Add docs for `DB seed` CLI command + separate page to explain how to set them up
=> Add db seed docs

docs/cli-console.mdx, docs/getting-started.mdx, docs/middleware.mdx, docs/mutation-resolvers.mdx, docs/mutation-usage.mdx, docs/query-resolvers.mdx, docs/query-usage.mdx, docs/ssr-query.mdx, docs/use-infinite-query.mdx, docs/use-mutation.mdx, docs/use-paginated-query.mdx, docs/use-query.mdx, sidebars.js
For https://github.com/blitz-js/blitz/pull/1160
=> Add docs for useMutation and customizing the `Ctx` type

docs/database-overview.mdx
A short explanation how to setup a PostgreSQL database with docker-cmpose for an easier transition to PostgreSQL.
=> Explanation how to setup local PostgreSQL database with docker-compose.

docs/contributing.mdx
Hopefully this makes contributing to the main blitz repo a bit easier, as I had a few difficulties understanding how to do it myself
=> Improve instructions for first-time contributors

docs/writing-recipes.mdx
I knew that I saw the explanation how to do this in Slack but I think it would be nice to have this inside the docs as well.
=> Test recipe locally

docs/tutorial.mdx
=> docs(tutorial): incremental numbering

docs/authorization.mdx
This PR matches the DOCs with the new Ctx type after 0.24.0
=> Updates authorization docs to match new Ctx

docs/how-the-community-operates.mdx
Move Simon Knott from L2 maintainers & Add Patrick Engelkes for L1 maitainers & remove Ivan from L1 maintainers.
=> Move Simon Knott from L2 maintainers & Add Patrick Engelkes for L1 maitainers & remove Ivan from L1 maintainers.

docs/auth.mdx
This PR removes an unnecessary word from the sentence.
=> Correct Text Error

docs/tutorial.mdx
While building my first Blitz project, I noticed a few inconsistencies between Blitz's generated code & the tutorial, which I aim to fix here.
I've never used Blitz before, so I apologize if any changes I made are incorrect.
Thanks! :)
=> Make tutorial consistent with generated code

docs/how-the-community-operates.mdx
it looks like a really nice project (: anxious to test it out..
just started sketching something with next + prisma, and this might fit better
=> Fix typo on "how the community operates" text

docs/tutorial.mdx
It should be `updateChoiceMutation`.
=> Fix Function Name in Tutorial

docs/how-the-community-operates.mdx
Adding myself to L1 Maintainers in the `how-the-community-operates.mdx`
Note: I think I have to update the docs version, but the ReadMe says versions are added to the `versions.json`. I could not find this file, and current version in package.json is listed as `0.0.0`. I would like some feedback on this.
=> Added flavio to L1 Maintainers

docs/get-static-props.mdx
Easy reading and easy navigation for others
=> Fix url bug in docs

docs/passportjs.mdx
Documentation changes associated with https://github.com/blitz-js/blitz/pull/1564
=> Updates passportAuth documentation with per strategy authentication options.

docs/cli-routes.mdx, sidebars.js
Linked PR: [#1478](https://github.com/blitz-js/blitz/pull/1478)
Add documentation for `blitz routes`
=> Add routes cli doc

docs/database-seeds.mdx
=> Renamed 'dummy data' to 'test data' to fix linter

docs/authorization.mdx, docs/cli-build.mdx, docs/session-management.mdx, package.json, yarn.lock
Removing the unstable_ prefix from the auth documentation.
=> Removed unstable prefix from auth

docs/tutorial.mdx
This line needs to be changed by the end user as well, highlighted accordingly.
=> Highlight changed line in tutorial

docs/tutorial.mdx
Inline with the discussion on https://github.com/blitz-js/blitz/issues/1606#issuecomment-751389484 I've moved the note about ZSH to under the first place it would be needed to make it clearer for the reader.
=> Move ZSH note to below first usage of blitz generate all

docs/cli-start.mdx, docs/deploy-render.mdx
Update docs for https://github.com/blitz-js/blitz/pull/1623
=> Update docs to add note about `blitz build` before starting prod

docs/tutorial.mdx
I stumbled over this bit in the tutorial. My changes intend to make it clearer what to type and what output to expect.
=> tutorial db migration cosmetics

docs/session-management.mdx
Added `domain` type to SessionConfig
Also added missing `method` type to SessionConfig
=> Add missing types to SessionConfig

docs/auth-utils.mdx, sidebars.js
For https://github.com/blitz-js/blitz/pull/1667
=> Add docs for SecurePassword

docs/contributing.mdx
If works for others, open PR.
https://blitzjs.slack.com/archives/C011EQ0J75M/p1600924782000100?thread_ts=1600913127.016200&cid=C011EQ0J75M
=> Fix how to cli development

docs/cli-prisma.mdx, sidebars.js
https://github.com/blitz-js/blitz/pull/1685
=> Add docs for `blitz prisma` command

docs/image-optimization.mdx
Co-authored-by: Brandon Bayer <b@bayer.ws>
=> Update image docs for next.js 10.0.5

docs/tutorial.mdx
While the tutorial shows the full example of `app/questions/queries/getQuestions.ts`, it shows a partial code of `app/questions/queries/getQuestion.ts`. So, I added imports and some declarations for the sake of consistency.
I also did some cleanups to make the tutorial more precise.
=> Polish the tutorial to make it more precise

docs/cli-db.mdx, docs/database-overview.mdx, docs/deploy-heroku.mdx, docs/deploy-render.mdx, docs/deploy-vercel.mdx, docs/tutorial.mdx
Co-authored-by: Brandon Bayer <b@bayer.ws>
=> Update docs for prisma 2.13+ support

docs/auth-utils.mdx
https://github.com/blitz-js/blitz/pull/1721
=> add docs for hash256() and generateToken()

new-site/app/components/DarkModeToggle.js
=> Fixed dark mode toggle on page load

docs/prisma.mdx, sidebars.js
https://github.com/blitz-js/blitz/pull/1720
=> Add docs for `makeServerOnlyPrisma()`

docs/tutorial.mdx
Hello :) I've been working through the tutorial. It's very useful. I just had some suggestions on some parts that I found a little confusing.
I also noticed on [line 659](https://github.com/blitz-js/blitzjs.com/blob/main/docs/tutorial.mdx#L659) there's a `refetch()` but it's not destructed from `useQuery`, and it's not included in the preceding code block (lines 603-625). Is that refetch needed? Currently the final step gives an error - refetch is not defined.
=> Improve tutorial doc

docs/file-structure.mdx, docs/testing.mdx, sidebars.js
https://github.com/blitz-js/blitz/pull/1725
=> add docs for new jest integration

docs/prisma.mdx
https://github.com/blitz-js/blitz/pull/1762
=> docs for makeServerOnlyPrisma -> enhancePrisma

docs/writing-recipes.mdx
See https://github.com/blitz-js/blitz/pull/1764
=> Mention "transformPlain"

src/pages/index.js
See: https://github.com/blitz-js/blitz/pull/1775
=> rename chakra recipe to chakra-ui

docs/maintainers.mdx
I described the new `#lang-*` channel. What do you think? :)
=> Update slack info for maintainers

docs/authorization.mdx, docs/session-management.mdx
https://github.com/blitz-js/blitz/pull/1796
=> Update docs for new isAuthorized improvements 

docs/session-management.mdx
https://github.com/blitz-js/blitz/pull/1806
=> Update docs for PublicData changes

docs/resolver-server-utilities.mdx
https://github.com/blitz-js/blitz/pull/1821
=> update canary docs for `pipe.resolver` rename to `resolver.pipe`

docs/authorization.mdx, docs/resolver-server-utilities.mdx
https://github.com/blitz-js/blitz/pull/1824
=> Remove docs for `resolver.authorizeIf` and `session.$authorize()` 

docs/blitz-config.mdx, docs/cli-dev.mdx, docs/cli-start.mdx, docs/custom-server.mdx, docs/deploy-heroku.mdx, docs/deploy-render.mdx, docs/get-static-paths.mdx, docs/get-static-props.mdx, docs/getting-started.mdx, docs/image-optimization.mdx, docs/postgres.mdx, docs/tutorial.mdx, new-site/README.md, new-site/package.json, sidebars.js
https://github.com/blitz-js/blitz/pull/1872
=> update docs for `blitz start` to `blitz dev` change

docs/session-management.mdx
Relevant PR in Blitz.js [1807](https://github.com/blitz-js/blitz/pull/1807)
=> Add explanation for initialPublicData of useSession.

docs/blitz-config.mdx
Documentation for [this PR](https://github.com/blitz-js/blitz/pull/1909)
=> Clear Console in blitz.config.js

docs/background-processing-with-quirrel.mdx, sidebars.js
This PR adds a new chapter called "Backend Architecture" that contains a guide on how to use Quirrel with Blitz.
=> Blitz x Quirrel docs

app/components/home/Footer.js
Just a pretty small update on website's footer, changed from 2020 to 2021
=> Footer date updated to 2021

app/layouts/ContentsLayout.js
I use vscode prettier so it may different than the one used in the project , i've tested the link it should work Thanks for @flybayer for the hint
=> Solving 404 url edit link Issue #371

app/pages/docs/tutorial.mdx
I noticed that the parameter for CreateQuestion doesn't match the example - Proposing a fix
=> Fix input param for CreateQuestion

app/pages/docs/authorization.mdx
=> Add ctx examples

app/pages/docs/authorization.mdx
Syntax error on line 296 of app/pages/docs/authorization.mdx
=> Syntax error on line 296.

app/pages/docs/query-usage.mdx
=> fix link to invokeWithMiddleware

app/pages/docs/passportjs.mdx
I have added to the "Third Party Login with Passport.js" page to document this change https://github.com/blitz-js/blitz/pull/2058.
=> Add docs for accessing ctx in `passportAuth`

app/pages/docs/contributing.mdx
This helps users running into https://github.com/blitz-js/blitz/issues/2072 identify a solution
=> Add Preconstruct errors section

app/pages/docs/templates.mdx
=> small typo fix in templates.mdx

app/pages/docs/how-the-community-operates.mdx
=> Adding kevinlangleyjr as L1 Maintainer.

app/pages/index.js
=> chore: Fix "GitHub" capitalisation

app/pages/docs/error-handling.mdx, app/pages/docs/error-pages.mdx
Just putting this here for posterity because [I was confused](https://github.com/blitz-js/blitz/issues/2131) by this as a newcomer to blitz
=> Add docs for Error Handling components

app/pages/docs/deploy-heroku.mdx
There was a little typo that i've fixed
=> Correction of typo in deploy-heroku.mdx 

app/core/components/SponsorPack.js, app/core/navs/documentation.json, app/pages/docs/blitz-config.mdx, app/pages/docs/cli-codegen.mdx, app/pages/docs/css.mdx, app/pages/docs/deploy-render.mdx, app/pages/docs/link.mdx, app/pages/docs/resolver-server-utilities.mdx, app/pages/docs/route-manifest.mdx, app/pages/docs/use-paginated-query.mdx, app/pages/docs/why-blitz.mdx, blitz.config.js
CC https://github.com/blitz-js/blitz/pull/2042
=> Document Routes Manifest

app/pages/docs/session-management.mdx
=> Fixing minor issue in Session Docs

app/pages/docs/how-the-community-operates.mdx
=> Add myself as L1 Maintainer

app/pages/docs/tutorial.mdx
The instructions of data migration is not clear in the tutorial, as described in https://github.com/blitz-js/blitzjs.com/issues/436
The last two issues are remained to be fixed.
=> Fix the first two issues of #436

.alexrc.js, app/pages/docs/how-the-community-operates.mdx
Forgot to add my personal webpage.
=> Edit Dieman's personal website

app/pages/docs/how-the-community-operates.mdx
=> new maintainer TommasoBruno added

app/pages/docs/use-infinite-query.mdx, app/pages/docs/use-paginated-query.mdx
Hey,
I added small descriptions to `useInfiniteQuery` and `usePaginatedQuery`. 
Thereby the user doesn't have to google if she/he doesn't know one of those query types.
antony :)
=> Added description to `useInfiniteQuery` and `usePaginatedQuery`

README.md, app/core/components/docs/Card.js, app/core/components/docs/Card.module.css, app/core/styles/utilities.css, app/pages/docs/api-routes.mdx, app/pages/docs/cli-db.mdx, app/pages/docs/cli-start.mdx, app/pages/docs/contributing.mdx, app/pages/docs/database-overview.mdx, app/pages/docs/deploy-heroku.mdx, app/pages/docs/deploy-vercel.mdx, app/pages/docs/error-pages.mdx, app/pages/docs/get-started.mdx, app/pages/docs/get-static-props.mdx, app/pages/docs/image-optimization.mdx, app/pages/docs/mutation-usage.mdx, app/pages/docs/query-usage.mdx, app/pages/docs/resolver-server-utilities.mdx, app/pages/docs/rpc-specification.mdx, app/pages/docs/static-html-export.mdx, app/pages/docs/templates.mdx, app/pages/docs/tutorial.mdx, blitz.config.js, package.json, tailwind.config.js, yarn.lock
Replaced admonitions with a custom component. This lets us customize it as we like and we no longer need to use ``
=> Admonitions --> Cards

app/pages/docs/blitz-config.mdx, app/pages/docs/get-started.mdx
This adds documentation for proxy-support added by the following pull request. 
https://github.com/blitz-js/blitz/pull/2264
=> add info for proxy-support https://github.com/blitz-js/blitz/pull/2264

app/pages/docs/custom-server.mdx, app/pages/docs/writing-recipes.mdx
This documentation complements the changes in https://github.com/blitz-js/blitz/pull/2169
=> Documentation for new schema.prisma transform utilities

app/core/navs/documentation.json, app/pages/docs/deploy-railway.mdx
Added guide to deploy blitz to [Railway](https://railway.app)
=> Create guide to deploy to Railway

app/core/components/DarkModeToggle.js
changes so that text toggles depending on theme selected. Also removed outline around toggle that stays when clicked.
resolves #463
=> Toggling text and removing outline

app/pages/docs/get-server-side-props.mdx, app/pages/docs/get-static-props.mdx, app/pages/docs/pages.mdx
This is documentation related to the prefetching techniques made possible by https://github.com/blitz-js/blitz/pull/1940 and https://github.com/blitz-js/blitz/pull/2281.
=> Documentation about prefetching and dehydratedState

app/pages/docs/pages.mdx
Fixes  https://github.com/blitz-js/blitz/issues/2336
@flybayer  Please have a look at this PR. Let me know if you need any changes :).
Thanks
=> Documentation Improvement: Page.authenticate implies Page.suppressFirstRenderFlicker 

app/pages/docs/authorization.mdx
Cc https://github.com/blitz-js/blitz/pull/2359
=> Document authenticate.redirectTo: RouteManifest

app/pages/docs/impersonation.mdx
If you try to copy-paste the examples there's a missing import
=> Missing import

app/pages/docs/resolver-client-utilities.mdx
hey,
I added some comments to getQueryKey and invalidateQuery because I couldn't figure out their purpose the first time :)
=> Add some comments to getQueryKey and invalidateQuery

app/pages/docs/route-params-query.mdx, app/pages/docs/routing.mdx
hey
I added some references from dynamic routing to `useParam`, `useParams`, `useRemoteQuery`, and reversed.
=> Add bilaterial reference between dynamic routing and useParam/useRouterQuery

app/core/navs/documentation.json, app/pages/_app.js, app/pages/docs/blitz-config.mdx, app/pages/docs/contributing.mdx, app/pages/docs/custom-server.mdx, app/pages/docs/database-overview.mdx, app/pages/docs/eslint-config.mdx, app/pages/docs/husky-config.mdx, app/pages/docs/impersonation.mdx, app/pages/docs/postgres.mdx, app/pages/docs/prettier-config.mdx, app/pages/docs/resolver-client-utilities.mdx, app/pages/docs/resolver-server-utilities.mdx, app/pages/docs/route-params-query.mdx, app/pages/docs/routing.mdx, app/pages/docs/testing.mdx
Documentation is for feature https://github.com/blitz-js/blitz/pull/2447
First time writing documentation in blitz so please be savage with the feedback :)
=> feat: add documentation for customServer.hotReload

app/core/components/Header.js, app/core/navs/documentation.json, app/pages/docs/utilities.mdx
I know this is pretty short, not sure if I provided enough detail. Please provide as much feedback as you can. This is my first time writing docs.
Docs for: https://github.com/blitz-js/blitz/pull/2441
=> adds documentation for utility functions

app/core/navs/documentation.json, app/pages/docs/error-boundary.mdx, app/pages/docs/error-handling.mdx
Add docs for new errorboundary component: https://github.com/blitz-js/blitz/pull/2480
=> adds documentation for utility functions (#498)

.alexrc.js, app/core/navs/documentation.json, app/pages/docs/blitz-config.mdx, app/pages/docs/css.mdx, app/pages/docs/eslint-config.mdx, app/pages/docs/get-started.mdx, app/pages/docs/image-component.mdx, app/pages/docs/resolver-server-utilities.mdx, app/pages/docs/rewrites.mdx, app/pages/docs/script-component.mdx, app/pages/docs/static-files.mdx
Co-authored-by: Brandon Bayer <b@bayer.ws>
=> add docs for nextjs 11

app/pages/docs/how-the-community-operates.mdx
Add @abuuzayr as L1 Maintainer
=> Add @abuuzayr as L1 Maintainer

app/pages/docs/authorization.mdx, app/pages/docs/resolver-server-utilities.mdx, app/pages/docs/session-management.mdx, app/pages/docs/testing.mdx, app/pages/index.js
Changing casing of `TypeScript` in a few places.
=> Change Typescript to TypeScript

app/pages/docs/authorization.mdx, app/pages/docs/multitenancy.mdx, app/pages/docs/resolver-server-utilities.mdx, app/pages/docs/session-management.mdx, app/pages/docs/testing.mdx, app/pages/index.js
[Blitz.js PR](https://github.com/blitz-js/blitz/pull/2634)
=> Add example - redirectAuthenticatedTo as a function

app/pages/docs/writing-recipes.mdx
See https://github.com/blitz-js/blitz/pull/2693
Edit: quick link to the vercel preview:
https://blitzjs-com-git-fork-markhughes-feature-2693-add-913c57-blitzjs.vercel.app/docs/writing-recipes#modifying-blitz-config
=> Add docs for addBlitzMiddleware

app/pages/docs/passportjs.mdx
Lines 306-308 refer to Twitter and Guthub; this example is Auth0
=> Clean up Auth0 example

app/pages/docs/blitz-config.mdx
Linked to https://github.com/blitz-js/blitz/pull/2888
=> Update blitz config docs and add info about log type

app/pages/docs/session-management.mdx
=> Update session management docs about auto-refresh

app/pages/docs/writing-recipes.mdx
=> New recipes transformers (and some formatting)

app/pages/docs/cli-install.mdx
Documentation for blitz-js/blitz#2954
Page updated: https://blitzjs-com-git-installer-yes-blitzjs.vercel.app/docs/cli-install
=> `blitz install --yes`

app/pages/docs/cli-db.mdx
[Blitz PR](https://github.com/blitz-js/blitz/pull/2962)
=> Add "file" option in "blitz db seed" docs

app/pages/docs/custom-server.mdx
Noticed this minor typo while reading through your docs.
=> Remove duplicated lines in example code

app/pages/docs/get-server-side-props.mdx, app/pages/docs/get-static-props.mdx
[blitz pr](https://github.com/blitz-js/blitz/pull/2932)
=> Add gsp/gssp redirect.destination examples using blitz routes

app/pages/docs/deploy-railway.mdx
This is a small change to include the build script within a code block in line 81 and line 82
=> Add the build script within code block

app/core/navs/documentation.json, app/pages/docs/deploy-docker.mdx
[`/docs/deploy-docker`](https://blitzjs-com-git-docker-blitzjs.vercel.app/docs/deploy-docker)
=> Deploy Using Docker

app/pages/docs/session-management.mdx
This PR addresses: https://github.com/blitz-js/blitzjs.com/issues/614
=> Document secureCookies flag and relationship with sameSite flag

app/pages/docs/cli-build.mdx, app/pages/docs/cli-codegen.mdx, app/pages/docs/cli-console.mdx, app/pages/docs/cli-db.mdx, app/pages/docs/cli-dev.mdx, app/pages/docs/cli-export.mdx, app/pages/docs/cli-generate.mdx, app/pages/docs/cli-install.mdx, app/pages/docs/cli-new.mdx, app/pages/docs/cli-prisma.mdx, app/pages/docs/cli-start.mdx, app/pages/docs/environment-variables.mdx
=> Add docs for setting custom app env name

app/pages/docs/multitenancy.mdx, app/pages/docs/tutorial.mdx
I just read a part of the documentation and found :
- a small error "from" -> "form"
- a small error on undefined "organizationId" binding 
- outdated code snippets on tutorial (using plain strings instead of Routes object)
Thanks for your amazing work !
=> Small doc correction and code snippets update (new Routes object)

app/pages/docs/blitz-config.mdx, app/pages/docs/query-usage.mdx, app/pages/docs/resolver-server-utilities.mdx, app/pages/docs/troubleshooting.mdx
Still reading this (amazing !) documentation and found few little errors.
Thanks for your work !
=> Small corrections on documentation

app/pages/docs/babel-config.mdx, app/pages/docs/prettier-config.mdx, app/pages/docs/rpc-specification.mdx
Still reading the documentation and found 3 very small corrections.
Thanks !
=> Small doc corrections

app/core/components/Search.js
=> fix HTML titles are now displayed in HTML tag format.

app/pages/docs/how-the-community-operates.mdx
Add @shellord as L1 maintainer
=> Add @shellord as L1 maintainer

app/pages/docs/database-seeds.mdx
marak's faker.js has been gone for a while now, I've updated the database-seeds page to refer to a new faker alternative.
=> update faker.js reference

app/core/navs/documentation.json
The docs page is not ready yet. We'll fill it up soon.
=> Remove get started with nextjs

app/pages/docs/query-usage.mdx
closes https://github.com/blitz-js/blitzjs.com/pull/693
=> Remove mention of revoke-with-middleware

app/pages/docs/rpc-specification.mdx, package-lock.json, yarn.lock
Updated docs for this PR
https://github.com/blitz-js/blitz/pull/3421
=> Add resolverPath docs

app/pages/docs/code-of-conduct.mdx
Addressed issue no. [707](https://github.com/blitz-js/blitzjs.com/issues/707)
=> Replace outdated url with project github repo url

app/pages/docs/passportjs.mdx
Mainly adding these two parts in the doc:
```
import { passportAuth } from "@blitzjs/auth"
import { api } from "app/blitz-server"
```
And the `api()` warapper.
=> Update Passportjs docs.

app/pages/docs/database-seeds.mdx
The seed command was wrong - this is the fix :)
=> fix typo in seed command

app/pages/docs/upgrading-from-framework.mdx
https://github.com/blitz-js/blitz/pull/3788
=> import getAntiCSRFToken from @blitzjs/auth

app/pages/docs/upgrading-from-framework.mdx
For PR: https://github.com/blitz-js/blitz/pull/3771
=> Add AuthenticatedSessionContext to import map in upgrade page

app/pages/docs/auth-setup.mdx
=> docs: fix imports blitz client/server

app/pages/docs/blitzjs-next.mdx
- Add __Example__ headings to client & server sections of @blitzjs/next
- Add __API__ headings with __Arguments__ & __Returns__ for both the client & server sections of @blitzjs/next
=> Improve the @blitzjs/next documentation

app/core/navs/documentation.json
Closes https://github.com/blitz-js/blitzjs.com/issues/762
=> Update docs sections headers

app/core/navs/documentation.json, app/pages/docs/cli-console.mdx
Docs for https://github.com/blitz-js/blitz/pull/3863
=> Add blitz console docs

app/pages/docs/tutorial.mdx
=> docs: add restart after data migration in tutorial

app/pages/docs/blitz-config.mdx
=> Remove isomorphicResolverImports from docs

app/core/navs/documentation.json, app/pages/docs/logging.mdx
Docs for https://github.com/blitz-js/blitz/pull/3886
=> Add logging section to the docs

app/core/components/Search.js, app/pages/docs/[...wildcard].js
- Update algolia credentials
- Create a  wildcard route in `/docs/[...wildcard]` that redirects to `/docs` permanently
=> Update algolia credentials & set wildcard for docs if not found

app/pages/docs/authorization.mdx
Docs for https://github.com/blitz-js/blitz/pull/3902
=> Page authenticate role

app/pages/docs/use-paginated-query.mdx
Documentation for issue: https://github.com/blitz-js/blitz/issues/3923
=> Range Pagination Documentation

app/pages/docs/contributing.mdx, app/pages/docs/file-structure.mdx, app/pages/docs/learning-path.mdx, app/pages/docs/manifesto.mdx, app/pages/docs/prisma.mdx, app/pages/docs/testing.mdx, app/pages/docs/tutorial.mdx
In reference to https://github.com/blitz-js/blitz/pull/3985
=> Update testing documentation to use vitest

app/pages/docs/impersonation.mdx
Update wording on impersonation docs.
=> Updating wording on impersonation

app/core/navs/documentation.json, app/pages/docs/usage-next-13.mdx
Docs for https://github.com/blitz-js/blitz/pull/4079/ and https://github.com/blitz-js/blitz/pull/4103
=> Next 13 App Directory Docs

app/pages/docs/prisma.mdx
The list was out of order which caused some confusion (as evident by my initial commit).
=> chore(docs): correct list order

app/pages/docs/middleware.mdx
https://github.com/blitz-js/blitz/pull/4296
=> Update import location of `BlitzServerMiddleware`
