blitz-js/blitzjs.com

docusaurus.config.js

👋 team,
I am working on DocSearch. [We have an integration for Docusaurus](https://docusaurus.io/docs/en/search#enabling-the-search-bar). We thought it is a shame you can not also used this search that you can [find on reactjs for example](https://reactjs.org/).
This PR will add DocSearch to the documentation website. It will allow an user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.
Let me know if you need anything.

feat(website): add DocSearch as recommended by docusaurus

---

src/theme/Footer/footer_styles.css
src/theme/Footer/index.js
src/theme/Footer/styles.module.css

Closes #49
The current Footer content comes from `docusaurus.config.js`. 
Only a few properties are possible in that document, these include: style, links, logo,and copyright. 
I found out about swizzling. It's similar to shadowing in Gatsby.
https://v2.docusaurus.io/docs/using-themes/#swizzling-theme-components
`yarn run swizzle @docusaurus/theme-classic Footer`
Used that to create a custom Footer component, which still takes information from the config file. Then, added the Vercel link in `theme/Footer`.
I had one issue. I wanted to change the default color for links, but could not add custom styles by inserting styles in the generated `styles.module.css`. So I created a `footer_styles.css` file in the Footer folder and imported it.

add vercel to footer, swizzle Footer component

---

docs/basics/getting-started.md

Resolves the following error encountered in the Getting Started guide:
```
Type "Id" is neither a built-in type, nor refers to another model, custom type, or enum.
```

docs(getting-started): fix DB schema

---

docusaurus.config.js
src/components/AnnouncementBar/index.js
src/components/Navbar/index.js

Disabling dark mode for now so we can go live before everything is converted to theme-ui and dark mode styles fixed.

Temporarily disable dark mode until its styles get fixed

---

docs/route-params-query.mdx

This PR adds documentation for `useParam` hook in https://github.com/blitz-js/blitz/pull/637

Add documentation for `useParam` hook

---

docs/router.mdx

[In this PR](https://github.com/blitz-js/blitz/pull/677), `params` and `query` are added as return values for `useRouter` and `withRouter`.
So, update the documentation of the router object.

Fixed description of the `router` object's `query `and `params`

---

docs/middleware.mdx

Tiny correction to remove an unnecessary bracket in the local HTTP middleware example.

Remove extra bracket in local middleware example

---

docusaurus.config.js
src/components/DocPage/index.js
src/pages/index.js

This PR closes the issue of Added social preview images. #79

Added social preview images

---

docs/getting-started.mdx

Noticed exotic was typod, but while correcting wondered if 'exotic' is the best choice of word here. It's often used by westerners to mean `foreign to westerners`. Perhaps unusual is a more inclusive choice.

Correct typo in exotic, suggest change to unusual

---

docs/cli-console.mdx
docs/cli-generate.mdx
docs/tutorial.mdx

We'll want to wait for the next Blitz release before merging this (depends on https://github.com/blitz-js/blitz/pull/659), but it should be ready to review at least.
I started out with the goal of updating the REPL examples to use top-level await, but ran into overall flow issues with the tutorial now that model generation is in (specifically, manually creating the model definitions in `db/schema.prisma` followed by `blitz generate all` yields undesired results). Per feedback in Slack from Brandon and Adam, I made some fairly significant updates to the tutorial to reflect the current recommended way of doing things (as I perceive them, anyway). As a result, this turned into a bigger update than I had originally intended, but I think it results in a better user experience.

Update docs to show current generator and console usage

---

README.md
package.json
src/css/custom.css
yarn.lock

Closes: #98 
Upgraded to @theme-ui/prism 4.0-rc.1 for support for commented code highlighting like so:
```
const example = "not highlighted";
// highlight-start
const highlighted = true;
// highlight-end
const alsoHighlighted = true // highlight-line
```
Adds a custom CSS class to visually distinguish the highlighted lines.

Enable highlighting specific lines within code blocks

---

docs/tutorial.mdx

In the tutorial you update `new.tsx` to create a default question "Do you love Blitz?".  Then later make updates for "Listing Choices" in the `QuestionsList` component and `[questionsId].tsx`.  After we are given an example of what the page should look like, but no where do we add choices for this default question, which might create confusion if the choices code is working/etc.  
Adding the "Yes!" choice while creating the default question will make the result after listing choices match the tutorials outcome.

Update default question to include choice

---

docs/what-is-nextjs.mdx
docs/why-blitz.mdx
sidebars.js

This is based off of a conversation in slack that can be found here: https://blitzjs.slack.com/archives/CUA5KK1BR/p1593475057295400
What I'm trying to do here is provide a little context if a person is reading the docs and thinks "what is Next.js?". I feel this is enough info to get the gist and worse case scenario they can learn more at their site.
I adapted this from this doc [here](https://docs.magic.link/technologies/next-js-integration) and removed some info I felt like would only add confusion.
Also, I renamed the `Why would someone use Blitz instead of Next.js?` to `Why use Blitz instead of Next.js?` just to make it more readable.

Adding a "What is Next.js?" section

---

.github/workflows/main.yml
docs/query-usage.mdx
docs/use-infinite-query.mdx
docs/use-paginated-query.mdx
docs/use-query.mdx

Updated documentation for the update to react-query v2.
Implementation is [here](https://github.com/blitz-js/blitz/pull/720).

Update document for react-query v2

---

docs/tutorial.mdx

This closes #103 
I've added syntax highlighting to the tutorial page but I ran into some small issue or maybe I overlooked something.
In the last part, I wanted to highlight the code blocks separately instead of highlighting it all as I did now. I don't know if that makes a huge difference for the user but I stumbled upon some weird behavior as you can see in the screenshots below. When I've already selected a piece of code, `handleVote()`, and I want to select the questions list it doesn't highlight the right code. It's off by two lines. When I remove the highlight at `handleVote()` it does work.
I've tried to 'cheat' to two-line offset in the second part but I wasn't able to grab the piece of code so I ended up highlighting the whole thing instead.

Added syntax highlighting to tutorial

---

docs/deploy-vercel.mdx

I noticed that when trying to deploy to Vercel it was hanging at the migration step. It looks like this issue was resolved in blitz-js/blitz#786, but depends on `NODE_ENV` being set to production for the build step. I've updated the docs to reflect the change required for the migrations to proceed.

Set NODE_ENV to production when migrating

---

docs/deploy-render.mdx

Updated the example YAML to include a new key/value pair that fixed deploy issues I was having when deploying to render.com
Snippet added:
```
envVars:
- key: NODE_ENV
value: production
```
The fix was suggested by @flybayer and the slack message is [here](https://blitzjs.slack.com/archives/C011EQ0J75M/p1597416891168400?thread_ts=1597383102.161700&cid=C011EQ0J75M)

Updated "Deploy To Render" Yaml to include Key of NODE_ENV

---

docs/use-infinite-query.mdx
docs/use-paginated-query.mdx

I have updated the docs for usePaginatedQuery and useInfiniteQuery. Both of them now reference the projects db table (rather than products) so anyone can copy/paste the code into a new blitz project.
The usePaginatedQuery example has been updated to calculate the hasMore logic on the server, in line with bug fix #858 in the blitz repo.

usePaginatedQuery docs example incorrect #129

---

docs/cli-new.mdx

Adds documentation for a `--no-git` switch/flag for `blitz new`. 
Depends on https://github.com/blitz-js/blitz/pull/905.

Add "no-git" switch documentation for "blitz new" 

---

docs/auth.mdx

This is a minor change in terms of structure, but removes all of the boilerplate that is now available standard in a Blitz app.
* Model definitions
* Middleware installation
* Auth queries, mutations, and validation
* Auth error boundaries
I think there's more we can do to make the docs easier to digest, but the first step is to remove all the heavy content that's no longer required.

Remove boilerplate from auth docs

---

docs/deploy-render.mdx

Since the webapp and the database needs to be in the same region for the `DATABASE_URL` to work without hassle, I added it

Added region to render template

---

docs/auth.mdx

Updated docs for `useSession` that now returns `isLoading` state.
Related to this PR: https://github.com/blitz-js/blitz/pull/936

Update useSession docs with isLoading property

---

docs/auth.mdx

* Closes #149 
* This was done just by looking at the Browser Dev Tools. I believe the whole document _should_ re-checked with the current implementation.
* Maybe this already does some good.

document the anti-csrf token storage

---

docs/passportjs.mdx

Removed single quotes from `redirectUrl` example and added an additional example using pathname from router.

Updated passportjs.mdx

---

docs/database-overview.mdx

Helps close issue [#1044](https://github.com/blitz-js/blitz/issues/1044) in the `blitz-js/blitz` repo.
The db provider value is no longer an array with `sqlite` and `postgres`. When switching from using SQLite to PostgreSQL the developer will need to specify the new db provider value in `db/schema.prisma`

Add step when switching from SQLite to PostgreSQL

---

docs/cli-start.mdx

This is the sister PR to https://github.com/blitz-js/blitz/pull/1137
This PR adds a `--no-incremental-build` command flag to the docs.

Add new `--no-incremental-build` command flag

---

docs/cli-install.mdx

- Docs show `g` but it should be `i`

Fix blitz install alias

---

docs/passportjs.mdx

The current link to passport.js doesn't work due to something wrong on their side. I've changed it to their home page instead so that it doesn't require a google search to find them.
If possible, please add the `hacktoberfest-accepted` label to the PR :).

Changing broken link to passport.js

---

docs/contributing.mdx
docs/how-the-community-operates.mdx
docs/maintainers.mdx
docs/passportjs.mdx
src/components/DocItem/index.js
src/pages/index.js

I didn't like how GitHub was misspelt on the main page so thought I'd contribute this little fix. Whilst looking for `Github`, I also spotted Slack in lowercase and fixed it too.
If you decide to accept this PR and it's not too much of an ask, could you label the PR with `hacktoberfest-accepted`?

Fix casing in Slack and GitHub

---

docs/mutation-usage.mdx
docs/resolver-utilities.mdx
docs/use-infinite-query.mdx
docs/use-paginated-query.mdx
docs/use-query.mdx

Adding documentation for `setQueryData` added on https://github.com/blitz-js/blitz/pull/1291

Add documentation for setQueryData

---

docs/database-overview.mdx

Fixes the spelling of "environment" in the docs.

Fix typo in database overview page

---

docs/database-overview.mdx

default path is: `./docker-compose.yml`, not `./docker.compose.yml`
https://docs.docker.com/compose/compose-file/#service-configuration-reference

fix: docker.compose.yml to docker-compose.yml

---

docs/middleware.mdx

The example for the connect middleware uses the `cors` handler which actually exports a constructor. So it needs to be called before being used.

Fix example for connect middleware

---

docs/tutorial.mdx

You will see the following First time users will be anxious.
```
warn  - ./pages/index.tsx
Anonymous arrow functions cause Fast Refresh to not preserve local component state.
```

Not Anonymous arrow functions for Fast Refresh

---

docs/deploy-heroku.mdx
sidebars.js

This PR adds a page with instructions on how to deploy a new Blitz application to Heroku using Heroku Postgres. It closes #239.
I’m a little torn about these instructions, I’m not sure I’m completely happy with how much it seems to rely on the reader knowing about Heroku, its CLI, and pushing to it using git. I don’t want it to be a guide about creating applications on Heroku but also don’t want to assume that the reader is experienced with this.
Any pointers or improvements would be great.
<details>
<summary>Page screenshot</summary>
</details>

Add deploy to heroku instructions

---

README.md

I was updating the docs before and was following the READMe to update the version of the docs like it described. However, I later found out we don't need that section. This PR is to remove it to help reduce confusion.
Closes #266

removed versioning section from READMe

---

docs/deploy-heroku.mdx

Since most people following the guide may have just created a fresh project hosted on Github, maybe we could suggest `main` instead of `master`.

master is replaced by main in new github project

---

docs/api-routes.mdx

I was following the docs to authenticate through an API route and realized ```export default const`` in the code example is not valid after posting it in my code editor. This a small edit to clean it up. 
<table>
<tr>
<th>
Before
</th>
<th>
After
</th>
<tr>
<tr>
<td>
</td>
<td>
</tr>
</td>
</table>

Fix invalid syntax in API routes auth code example

---

docs/use-infinite-query.mdx
docs/use-paginated-query.mdx
docs/use-query.mdx

Remove `manual` option occurrences across queries pages since it seems to have been replaced by `enable`

Remove `manual` option occurrences

---

docs/cli-build.mdx

Looks like it was an example that was copy+pasted from `blitz start`

Remove bad example from Blitz Build docs

---

docs/image-optimization.mdx
sidebars.js

I have copied the documentation from the Next.js docs for [Image Component and Image Optimization](https://nextjs.org/docs/basic-features/image-optimization) and [next/image](https://nextjs.org/docs/api-reference/next/image) merging them both onto a single **Image Optimization** doc.

Add docs for Image component

---

docs/i18n-routing.mdx
sidebars.js

I've copied the Next.js docs on [Internationalized Routing](https://nextjs.org/docs/advanced-features/i18n-routing) into the Blitz documentation

Added documentation for i18n routing

---

docs/tutorial.mdx

The current code causes an error because the "FindManyQuestionArgs" type comes from Prisma.
This will help tutorial users by preventing this error and explicitly showing that they need to keep the Prisma imports from the code they are replacing.

Fix for "Listing Choices" portion of Tutorial

---

docs/tutorial.mdx

Closes: #293
- The `skip type definition` and `result return from getQuestions.ts` problem mentioned in the issue is my carelessness, content which generated from the latest version of BlitzJS works normally.
I found some other issues and  fix it, including: 
- `<Link />` component props:
- `include` options in getQuestion.ts
- keep up with latest generated contents

fix: fix outdated & incorrect code example

---

docs/tutorial.mdx

This PR reverts https://github.com/blitz-js/blitzjs.com/pull/297.
The sentence is actually a part of actual output of `blitz generate all question text:string choices:choice[]`. We need to run `blitz db migrate` after the second `blitz generate` command.

Roll back the sentence to the original output

---

docs/document-component.mdx
docs/session-management.mdx

There was a small spelling mistake: "Access" was spelled "Acess".

Fix typo in session-management.mdx and code block in document-component.mdx

---

docs/tutorial.mdx

I just finished [Blitz.js tutorial](https://blitzjs.com/docs/tutorial) and joined Blitz.js Discord but couldn't find the channel noted on the tutorial. (**#show-and-tell**) Guess it's recently renamed to **#built-with-blitz**? 
(Not sure if this PR is worth it since I know you guys are working on a new version doc that contains `docs/tutorial.mdx` too)

Change discord channel name in tutorial.mdx

---

docs/cli-generate.mdx

The example for creating a model with a `dateTime` field doesn't have the capital T. If the model is created with the lowercase t, the prisma migration fails.

Fix dateTime example on Scalar Fields

---

app/pages/docs/tradeoffs.mdx

Small typo on tradeoffs page I noticed when reading the docs.

Typo fix on tradeoffs page

---

app/navs/documentation.js
app/pages/docs/translations.mdx
app/pages/languages.js

I added a very simple languages page. It's only meant to track the progress of each translation (for now)
Also, I added a entry in the docs with a bit of information for everyone who wants to translate Blitz. It's meant to be used in this situations:
> — Hey, how can I help translating Blitz?
> — https://blitzjs.com/docs/translations

Languages and Translations entry

---

app/components/Search.js

When hovering the search button using the bright theme, the text colour would remain black, making it hard to read.

style: update search button styles

---

app/pages/docs/tutorial.mdx

Since the `updated` const isn't actually used, and since it's not present in the complete code block just below this one, I figured it could be removed 👍

don't store updateChoiceMutation in variable

---

app/pages/docs/tradeoffs.mdx

Corrected the word spawing as spawning in the "Single Threaded When Not Deployed Serverless" section.

Fix: Spelling of spawning corrected

---

app/pages/docs/api-routes.mdx

Should lines #24-25 be changed? I don't think there's a better place to link though.

Add type annotations to api-routes

---

app/pages/docs/deploy-render.mdx

There was unwanted properties that caused the build to fail,
so I removed them.

Fix render.yaml example of deploy-render `Without database`

---

app/pages/docs/database-overview.mdx

I ran into an issue when trying these steps out directly: updating the database URL changes the behavior of the app, but as soon as you go to commit those changes, tests will fail because `.env.test.local` will still contain an SQLite configuration instead of Postgres.
<details>
<summary>Error log</summary>
```
➜  blitz-redo git:(main) ✗ y test
yarn run v1.22.4
$ jest
FAIL   SERVER  app/auth/mutations/resetPassword.test.ts
● resetPassword mutation › works correctly
Failed: 1
3 | import { hash256, SecurePassword } from "blitz"
4 |
> 5 | beforeEach(async () => {
| ^
6 |   await db.$reset()
7 | })
8 |
at Env.beforeEach (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:46:24)
at Object.<anonymous> (app/auth/mutations/resetPassword.test.ts:5:1)
● resetPassword mutation › works correctly …
```

Update test env when switching to psql

---

package.json
postcss.config.js
yarn.lock

Tailwind just released a spanking new experimental library for just-in-time compilations a few days ago: https://blog.tailwindcss.com/just-in-time-the-next-generation-of-tailwind-css
For me who's using an underpowered laptop, developing on blitzjs.com was quite a pain as any change I made would trigger a CSS recompilation and my browser would struggle to apply the large css bundle as we enabled quite a few variants (perhaps we don't even use all the enabled variants, but since V2 was a fork off the tailwind website.. we didn't look into removing the unused variants)
While the library is experimental, I think it is sufficiently ready and will bring a lot of benefits by this simple small change. But of course, this is optional and we don't have to apply it if we don't want to :)

Optional chore: Add and use @tailwindcss/jit

---

app/pages/docs/api-routes.mdx

Very small but useful change here. The request parameters are typed but the types aren't imported.

Fix imports in api route example

---

app/core/styles/prism.css
remark/utils.js

Fixes #410 
This is an ugly hack, I must apologise. What we should do next is to find a different way to write the `// highlight-line`, `// highlight-start` and `// highlight-end` for syntax highlighting if we want to go about doing this better.

Apply code replacement for // highlight-line

---

app/pages/docs/deploy-render.mdx

When following the above example to deploy to render I received an error that I needed to pass the SESSION_SECRET_KEY. In this change I leverage Render's IaC capability to generate this secret at runtime so new users can quickly deploy without errors.

render.yaml fix to properly deploy to Render

---

app/pages/docs/deploy-render.mdx

I just deployed my blitz app to render.com and while I had been following official instructions I had noticed that two steps can be removed.
#421 introduced automatic `SESSION_SECRET_KEY` environment variable creation which makes steps about adding it manually not necessary anymore.

Remove redundant steps from `deploy-render.mdx`

---

app/pages/docs/css.mdx

Added a comment about TypeScript support for CSS Modules
URL: https://blitzjs-com-git-428-typescript-css-modules-blitzjs.vercel.app/docs/css#typescript-support

TypeScript Support for CSS Modules (css.mdx)

---

app/core/styles/utilities.css

This is an attempt to make a minimal change fix for the issue raised https://github.com/blitz-js/blitzjs.com/issues/431
This change makes sure the use of `<strong>` tags does not override the section's color. The text remains bold so I believe it's still differentiated enough.
I wouldn't be surprised if you'd like to go in a different direction with this change, perhaps adjusting the yellow or implementing a solution that would cover other tags. But wanted to start with suggesting the smallest fix I could find.
**Implementation note:** I was unable to use a CSS Tailwind class as I do not believe they support `color: inherit` (See Github Discussion https://github.com/tailwindlabs/tailwindcss/discussions/1361). I've used the direct CSS instead.
**Current**
**With change**
closes: …

Allow emphasised text to maintain color in dark-mode

---

app/pages/docs/tutorial.mdx

I got an error from running:
```sh
blitz generate resource choice text votes:int:default=0 belongsTo:question
```
the fix:
`blitz prisma format

Error in tutorial

---

app/pages/docs/cli-dev.mdx
app/pages/docs/cli-start.mdx

Hey,
I added the `--inspect` flag to the documentation of `blitz start` and `blitz dev` (see https://github.com/blitz-js/blitz/pull/1063)
antony :)

Added `--inspect` flag to blitz start and blitz dev

---

app/pages/docs/writing-recipes.mdx

This recommendation for writing a new recipe could be improved: the docs say that you can/should use a direct import of jscodeshift. You can do this, but it'll fail pretty soon: what a recipe really provides is a program parsed with the customTsParser, not a program parsed with the default parser.

Recommend customTsParser for building a new recipe

---

app/pages/docs/postgres.mdx

Hey,
more small changes: 
I've added some information about the location of `DATABASE_URL` and that the user has to run `docker-compose` before `blitz prisma migrate `.

Extend "run postgres via docker" section

---

app/core/styles/main.css

This pr is rather simple. It simply makes the scrolling when you scroll to another part of a page using an id button much smoother. For example, when you use the "Back to top" button in the footer, it won't jump up so quickly, it'll instead scroll. This is useful because it will surprise people less and it'll seem cleaner and less choppy too.

Add `scroll-behavior: smooth;` to main.css

---

app/pages/docs/tradeoffs.mdx

In the second to bottom section, (Advanced Backend Architecture), it reads '...especially compared *so* something....' Word fix to *to*

Typo in tradeoffs.mdx

---

app/pages/docs/impersonation.mdx

When you impersonate another use it would be a good idea to assumer their role too.
Most endpoints will be protected with some kind of authorizer e.g. `resolver.authorize("seller")` or `resolver.authorize("buyer")`. 
If you try and invoke these endpoints as an admin, they all need to be changed to `resolver.authorize(["seller", "admin"])` or `resolver.authorize(["buyer", "admin"])` etc.
If you assume the role of the user you're impersonating, you don't need to change anything.
In terms of security: 
- `startImpersonating` should only be available to admins, so it should be secured with `resolver.authorize("admin")`.
- we can allow `stopImpersonating` to be called without a role restriction as it is: the code already checks if `impersonatingFromUserId` is present in the session. If …

Avoid hardcoding "admin" role during impersonation

---

app/pages/docs/resolver-server-utilities.mdx

Hey,
I've added a small description to `resolver.authorize`, including the usage of `session.$authorize`.
This information could help developers testing their mutations or queries (see blitz-js/blitz#2363) 
antony :)

Add description to `resolver.authorize`

---

app/pages/docs/database-overview.mdx
app/pages/docs/postgres.mdx

- small improvements to docs (as discussed on discord) clarifying that test database must be different than main one.
- extension to `docker-compose.yml` containing pre-set test database - it has no volume on purpose as it's not something we need on test database

Test database notes

---

app/core/components/Header.js
app/pages/docs/auth-utils.mdx

https://github.com/blitz-js/blitz/pull/2473Cheers,
this PR adds documentation for the `setPublicDataForUser` (naming pending) API.
The API can be used to update session data for other user's to reflect permission/role changes directly, without the need to sign out and in again.
Feature PR: https://github.com/blitz-js/blitz/pull/2473

docs: document new setPublicDataForUser API

---

app/pages/docs/authorization.mdx

Rereading through the docs it's unclear what the use-case difference is between `useSession()` and `useCurrentUser()`.
This removes the mentioning of suppressing the first render since it's unrelated to the useSession vs useCurrentUser discussion. 
I still think we need a *reason* that you would use useCurrentUser. I'm not really sure what that would be though?

Clarify distinction between useSession & useCurrentUser

---

app/pages/docs/deploy-render.mdx

When working with TypeScript the build fails when we are not creating the model first. I can add a comment if you want mentioning that the models should be generated before the build first.
Here is an error from my recent project: ![Build error without generating models](https://i.imgur.com/1PaWqyx.png)

Add instruction for render.yaml

---

app/pages/docs/writing-recipes.mdx

This is a feature nobody asked for (maybe?) but it's something that I think was missing in the recipes; writing a custom message step while installing a recipe. 
Closes: ?
Adds new step type `printMessage`
```typescript
builder.printMessage({
successIcon: "😭",
stepId: "oops",
stepName: "Im so sorry :(",
message:
"This recipe can't edit your blitz.config.ts (yet), you can add the Blitz Guard middleware following these two steps: https://ntgussoni.github.io/blitz-guard/docs/middleware",
})
```
This prints the message in the following way

Adds builder.printMessage documentation

---

app/pages/docs/deploy-railway.mdx

I'm just getting started with Blitz. Following the Getting Started Guide and the section about deployment on Railway I ran into an HTTP 502 Bad Gateway error.
I figured out that the port the Blitz server is running on must be configured manually for Railway. One way is to modify the start script as already [described in a discussion](https://github.com/blitz-js/blitz/discussions/2335). Another way is to add a `PORT` variable to the railway environment.
Maybe it would be a good idea to add this piece of information to the Railway Deployment section?

Add info to set PORT for railway deployment

---

app/pages/docs/tutorial.mdx

I've found that the inline code of `blitz generate` command is unexpectedly separated. This PR change them to a single inline code.
I've also updated the outputs with the latest texts.

Fix unexpected inline code formatting in the tutorial

---

app/pages/docs/contributing.mdx

Removed the git command to add `upstream` from the "Sync your fork" section in Contributing doc since the `fetchRemote` script itself checks & adds `upstream` if required.
Link to the script for quick reference - 
https://github.com/blitz-js/blitz/blob/6adf7c02d4b7c9d3fd713e3f4f2bfd300e78830d/scripts/fetchRemote.sh
Also, would it make sense to add `git merge upstream/canary` also to the script and just let people run `./scripts/fetchRemote.sh` script to update their fork? If we're happy with that, I'll make that change and also update this PR to reflect that.

Update contributing doc - sync your fork section

---

app/pages/docs/multitenancy.mdx

Fix the `signup` mutation to make the user insertion return a user's memberships.
See https://discord.com/channels/802917734999523368/872490237719371826/872490241469083688

Update `signup` mutation in multitenancy.mdx

---

app/pages/docs/session-management.mdx

Resolves: #540 
Fixed dead link in 'Customize Session Persistence & Database Access' section of the session management docs. Replaced the dead link with the current default implementation of `SessionConfig`.

Fix: dead link in session management docs

---

app/pages/docs/tradeoffs.mdx

I identified this tradeoff as belonging to Node.js generally rather than Next.js specifically. I also removed the bit about serverless from the heading, as it implied (at least to me) that the serverless deployment was somehow multithreaded. Instead, I added another paragraph explaining why this tradeoff is irrelevant on at least some serverless platforms, while noting that deployment to Vercel specifically is not recommended.

Fix: clarify the single-threading tradeoff (#514)

---

app/pages/docs/custom-server.mdx

Custom server handles some routes twice, resulting in an error: `Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`
Reproducible for any not pre-defined route, e.g. `/abc`

Custom server example handles some routes twice resulting in an error

---

app/pages/docs/cli-generate.mdx

Related issue: https://github.com/blitz-js/blitz/issues/2747

document usage of optional types with zsh

---

app/core/navs/documentation.json
app/pages/docs/client-and-server.mdx

I added a new page to the docs as per this comment: https://discord.com/channels/802917734999523368/891631382877569054/892170181458149416.
I wanted to summarize what's executed on the server versus what's on the client as it seems helpful to have this kind of summary. Let me know what you think!
I also wanted to include an architecture diagram but wasn't happy with how it looks and didn't want to modify the original svg too much. 
Though I think this diagram would be super helpful, so I'd create an issue for that after this PR is merged. Unless you like how it could look right now (it's not included in this PR):

add docs on client vs server

---

app/pages/docs/postgres.mdx

the `docker-compose up` command -d requires that the `docker-compose` package is installed on the user's computer in addition to the docker package.
Now, docker supports the `compose` option natively. You can use `docker compose` instead.

updated command docker compose up -d

---

app/pages/docs/use-mutation.mdx
app/pages/docs/use-query.mdx

Updated the useQuery documentation to include a description of the useErrorBoundary option. I also tweaked the useMutation docs to include useErrorBoundary's type.
Resolves #548

Update useQuery and useMutation docs

---

app/core/navs/documentation.json
app/pages/docs/troubleshooting.mdx

During my investigation on https://github.com/blitz-js/blitz/pull/2792, I discovered the `DEBUG` environment variable.
I think this variable could have helped the reporter of https://github.com/blitz-js/blitz/issues/2751 to troubleshoot his issue on Blitz console.
I initiated a new section `troubleshooting` that can contains a lot of tips like that.
That could be a "must read" for future users that encounter an issue and need help debugging their Blitz projects.
Hope you'll like this 😄

add a troubleshooting part with debug logging

---

app/pages/docs/cli-generate.mdx

It took me longer than it should have done to understand the distinction between using the `--parent` flag and using `belongsTo:model` notation.
To generate the pages, mutations, queries AND model relationships for a parent:child pairing of models, you need to use both the `--parent` flag and set the `belongsTo:model` relationship.
I think the lines I have added to the docs are the minimal needed change to surface this info.

Update --parent documenation in cli-generate.mdx

---

app/pages/docs/tutorial.mdx

The previous order asked you to run `blitz console` earlier. That command resulted in errors since the generated files had to be updated first.
The unused file `app/choices/mutations/createChoice.ts` also needs to be deleted earlier.
Fixes #594

Improve the order of steps in tutorial

---

app/pages/docs/session-management.mdx

This is a simple PR to replace `muations` with `mutations`

fix: typo on folder name - Session Management page

---

app/pages/docs/query-usage.mdx

Use `invokeWithMiddleware` when calling queries on the server in `getServerSideProps`

docs: add invokeWithMiddleware for server queries

---

app/pages/docs/custom-server.mdx

The import of `log` in the docs example no longer works in the latest version of Blitz.

Fix import of log in custom server example

---

app/pages/docs/blitz-config.mdx
app/pages/docs/cli-generate.mdx

Docs for: https://github.com/blitz-js/blitz/pull/3068

Add docs for custom templates option

---

app/pages/docs/postgres.mdx

There's a typo on the `pre-dev` script for the `docker-compose` command.

Fix docker-compose command typo

---

app/core/components/Banner.js
app/core/components/Header.js
app/core/layouts/SidebarLayout.js
app/core/navs/documentation.json
app/pages/docs/blitz-pivot.mdx

I added a new page to the docs (to the `introduction` section, which I'm not sure is the best place?), a new banner informing about the pivot and pointing to the docs. I also made the redirects to `blitz-pivot` instead of `getting-started` as I thought it can be beneficial for people to first learn about the pivot before diving into getting started. No strong opinions here, though.

Add information about Blitz pivot

---

app/pages/docs/deploy-docker.mdx

Fix copying to files to wrong directory

Update example Dockerfile

---

app/pages/docs/writing-recipes.mdx

Documentation for https://github.com/blitz-js/blitz/pull/3006 / https://github.com/blitz-js/blitz/pull/3090

[Feature] Allow to run additional commands in the recipe installer

---

app/core/components/home/NewsletterForm.js

Currently in the documentation, if an email is very lengthy, it will overlap with the button(Icon). This PR is intended to fix that particular style issue.

[STYLE FIX]: Email input box style fix in footer

---

tailwind.config.js

fix #655
Preview: https://blitzjs-com-git-fork-eai04191-fix-code-wrap-blitzjs.vercel.app/docs/pages
`overflow-wrap: break-word` is also used in the `code` on GitHub and seems to be suitable for this usage.

Fix long words in code sticking out of the content box

---

app/core/components/home/HeroCode.js

Fixes this inconsistency:
From:
```
import createProject, {CreateProject} from "app/projects/mutations/createProject"
```
To:
```
import createProject, { CreateProject } from "app/projects/mutations/createProject"
```

"lint" the home page code editor inconsistency

---

app/pages/docs/auth.mdx

SuperTokens recently changed its URL from supertokens.io -> supertokens.com, this PR reflects that change

updating supertokens url in auth docs

---

app/pages/docs/contributing.mdx

While trying to set up the blitz projec on my macbook, I've encountered a few obstacles.
I've wrote them down, fixed them, and added the steps to the contribution guide!
The node 14 restriction should be fix if node-sass is updated to beyond 6.0.1 or something like that.
`sodium-native` that I honestly don't know what it does requires `autoconf` and `automake` to be installed my your mac machine
Hope this helps!
EDIT: now working on the new toolkit, I'm guessing it might not be relevant anymore and will be re-written. If thats the case feel free to close this PR :)

Add missing instructions for contributors

---

app/pages/docs/get-started.mdx

The named anchor `https://github.com/blitz-js/blitz#sponsors-and-donations` doesn't exist anymore.
Replaced it with `https://github.com/blitz-js/blitz#financial-contributors`.

fix dead link

---

app/pages/docs/passportjs.mdx

No clue why #700 was closed, this is exactly the same change.
`PassportAuth()` should be wrapped with `api()`, similar to how it's done at https://github.com/blitz-js/blitzjs.com/blob/d61b7176f9d5789397d0b8954cd64eb25bd26077/app/pages/docs/rpc-setup.mdx#blitz-rpc-with-nextjs-setup-nextjs.
Fixes blitz-js/blitz#3467.

docs: Wrap passport example with api() from blitz-server

---

app/core/navs/documentation.json
app/pages/index.js

- move why blitz up in the documentation sidebar
- update cta link to point to why-blitz

Update CTA link

---

app/core/components/home/Footer.js

"Hosted on Vercel" was missing from the footer.

Add missing hosted by vercel in footer

---

app/pages/docs/cli-generate.mdx

Docs for https://github.com/blitz-js/blitz/pull/3866

Docs for Custom Templates PR

---

app/pages/docs/tutorial.mdx

This PR adds instructions to restart Blitz in the Tutorial in order to avoid an `undefined` error.
Fixes #753

Add restart Blitz instruction in Tutorial

---

app/pages/docs/cli-generate.mdx

See also https://github.com/blitz-js/blitz/pull/4033

cli-generate: Use src instead of app folder

---

app/pages/docs/route-manifest.mdx

This will add a section on https://blitzjs.com/docs/route-manifest#query-parameters that describes how to use Hash URLs with Blitz and Next JS.
See also Discord.

Docs: Routes: Section on hash URLs

---

app/pages/docs/usage-next-13.mdx

Update: I tested this again with my test app at https://github.com/FixMyBerlin/blitz-test and it turns out you can run the page in root `/app/*` and include from `/src/*`. 
I updated this PR to a recommendation, because I still think its better to use `/src/app` for all blitz apps that use `/src/pages`.

Update usage-next-13.mdx: Clarify `/src/app` folder

---

app/pages/docs/usage-next-13.mdx

This is how the auth docs show it (https://blitzjs.com/docs/blitz-auth-with-next#add-blitz-server) and I assume all blitz apps with auth are set up. It is confusing when the app router docs show it differently.
At least I assume that the blitz-server still needs to share the cookie name(?)

Update usage-next-13.mdx: Still use `authConfig`

---

app/pages/docs/usage-next-13.mdx

The current migration guide https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#migrating-from-pages-to-app recommends 
>` pages/api/*` currently remain inside the pages directory.
I tried moving the existing files to the app directory but that fails. Likely because the new app/api directory works differently. However, in general there are app/api routes documented in https://nextjs.org/docs/app/building-your-application/routing/route-handlers so maybe with updated files we can migrate…

Update usage-next-13.mdx: Clarify that the API route need to stay in the pages folder

---

app/pages/docs/auth-server.mdx
app/pages/docs/rpc-config.mdx
app/pages/docs/rpc-setup.mdx

Docs for  https://github.com/blitz-js/blitz/pull/4341

Docs for Blitz RPC endpoint to the app directory
